time_stretch:
  enabled: true
  variations: 3
  min_factor: 0.6
  max_factor: 1.6
pitch_shift:
  enabled: true
  variations: 3
  min_semitones: -5
  max_semitones: 5
reverb_filter:
  enabled: true
  variations: 3
  min_room_scale: 10
  max_room_scale: 100
  cutoff_pairs:
  - !!python/tuple
    - 20
    - 20000
  - !!python/tuple
    - 300
    - 20000
  - !!python/tuple
    - 3000
    - 20000
  - !!python/tuple
    - 20
    - 16300
  - !!python/tuple
    - 20
    - 17500
  - !!python/tuple
    - 20
    - 18000
gain_chorus:
  enabled: true
  variations: 3
  min_gain: 2
  max_gain: 11
  min_depth: 0.1
  max_depth: 0.6
  rates:
  - 0.5
  - 1.0
  - 2.0
add_pause:
  enabled: true
  pause_threshold: 0.0033
  min_pause_duration: 1
  max_pause_duration: 5
processing:
  num_workers: 4
  cache_dir: null
  output_dir: null
